### ISSUE TITLE
The difference between your project and Baritone

### ISSUE THREAD

**Issue by Nidelon** [SMILEY4/Stevebot#2]
What is the difference between your project and Baritone? [Baritone](https://github.com/cabaletta/baritone)

**Comment by SMILEY4** [comment]
There isnt a huge difference (yet). I found baritone and thought it would be a fun problem to tackle myself. Stevebot is mainly a platform for me to experiment with ai in videogames.

**Comment by Nidelon** [comment]
Thanks for the answer :D
